sudo: required

language: generic

services:
 - docker
 
before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t heav2n/docker-react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true heav2n/docker-react-app npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "ap-northeast-2"
 app: "docker-react-study"
 env: "Dockerreactstudy-env"
 bucket_name: "elasticbeanstalk-ap-northeast-2-846414621579"
 bucket_path: "docker-react-study"
 on:
  branch: master
   
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_ACCESS_KEY
